export const bis11 = [
  {
    type: "matrix",
    name: "BIS11",
    isAllRowRequired: true,
    title:
      "People differ in the ways they act and think in different situations. This is a quiz to measure some of the ways in which you act and think. Read each statement and select the answer that DESCRIBES YOU BEST. Do not spend too much time on any statement. Answer quickly and honestly.",
    columns: [
      { value: 1, text: "Do not agree at all" },
      { value: 2, text: "Agree slightly" },
      { value: 3, text: "Agree a lot" },
      { value: 4, text: "Agree completely" },
    ],
    rows: [
      { value: "BIS_1", text: "I plan tasks carefully." },
      { value: "BIS_2", text: "I do things without thinking." },
      { value: "BIS_3", text: "I make-up my mind quickly." },
      { value: "BIS_4", text: "I am happy-go-lucky." },
      { value: "BIS_5", text: "I don’t 'pay attention'." },
      { value: "BIS_6", text: "I have 'racing' thoughts." },
      { value: "BIS_7", text: "I plan trips well ahead of time." },
      { value: "BIS_8", text: "I am self controlled." },
      { value: "BIS_9", text: "I concentrate easily." },
      { value: "BIS_10", text: "I save regularly." },
      { value: "BIS_11", text: "I 'squirm' at plays or lectures." },
      { value: "BIS_12", text: "I am a careful thinker." },
      { value: "BIS_13", text: "I plan for job security." },
      { value: "BIS_14", text: "I say things without thinking." },
      { value: "BIS_15", text: "I like to think about complex problems." },
      { value: "BIS_16", text: "I change jobs." },
      { value: "BIS_17", text: "I act 'on impulse'." },
      {
        value: "BIS_18",
        text: "I get easily bored when solving thought problems.",
      },
      { value: "BIS_19", text: "I act on the spur of the moment." },
      { value: "BIS_20", text: "I am a steady thinker." },
      { value: "BIS_21", text: "I change residences." },
      { value: "BIS_22", text: "I buy things on impulse." },
      {
        value: "BIS_23",
        text: "I can only think about one thing at a time.",
      },
      { value: "BIS_24", text: "I change hobbies." },
      { value: "BIS_25", text: "I spend or charge more than I earn." },
      {
        value: "BIS_26",
        text: "I often have extraneous thoughts when thinking.",
      },
      {
        value: "BIS_27",
        text: "I am more interested in the present than the future.",
      },
      { value: "BIS_28", text: "I am restless at the theater or lectures." },
      { value: "BIS_29", text: "I like puzzles." },
      { value: "BIS_30", text: "I am future oriented." },
    ],
  },
];
